### ISSUE TITLE
DTOs anlegen

### ISSUE THREAD

**Issue by kreaktiv** [kreaktiv/wetter#1]
Wetterdienst
- Name

StündlicheVorhersage
- Zeitpunkt (datetime)
- Temperatur (int)
- Bedingung (string)
- Regenrisiko (int)

TäglicheVorhersage
- Datum (datetime)
- TemperaturMax (int)
- TemperaturMin (int)
- Bedingung (string)
- Regenrisiko (int)

**Comment by kreaktiv** [comment]
Erster Entwurf der DTOs meinerseits.

**Comment by patricksadowski** [comment]
Für mein Empfinden sind das die Daten, die wir in einer Datenablage abspeichern möchten bzw. die einfachste Repräsentation der Daten im System. Wir werden weitere DTOs benötigen, die uns Daten verbinden oder in Beziehung setzen z. B.

Vorhersage
- Heute (array<StündlicheVorhersage>)
- Demnächst (array<TäglicheVorhersage>)

Deine vorgeschlagenen DTOs brauchen wir auf jeden Fall, also können wir damit beginnen. Weitere ergeben sich dann durch den Flow oder die eingesetzten Technologien.

**Comment by kreaktiv** [comment]
Ich habe die besprochenen DTOs umgesetzt und im Pull Request #4 zur Verfügung gestellt.
Bitte um Review.
